services:
  postgres:
    env_file : 
      - ../.env
    image: postgres:18.2-trixie
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/data
  norn.api:
    image: ${DOCKER_REGISTRY-}nornapi
    build:
      context: .
      dockerfile: Norn.Api/Dockerfile
    env_file:
      - ../.env
    depends_on: 
      - postgres
    ports:
     - "8080:8080"
  norn.WebApp:
    image : ${DOCKER_REGISTRY-}nornwebapp
    build :
      context: ../Norn.WebApp/nornWebApp
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200" 
  rabbitmq:
   env_file : 
    - ../.env
   image: rabbitmq:4.3.5-management
   container_name: nornrabbit
   ports:
     - "5672:5672"
     - "15672:15672"
  norn.emailservice:
    env_file : 
    - ../.env
    image: ${DOCKER_REGISTRY-}nornemailservice
    build:
      context: .
      dockerfile: Norn.EmailService/Dockerfile
    depends_on:
      - rabbitmq
  norn.signalRService:
    env_file : 
    - ../.env
    image: ${DOCKER_REGISTRY-}nornsignalrservice
    build:
      context: .
      dockerfile: Norn.SignaRService/Dockerfile
    ports:
      - "8008:8008" 
    depends_on:
      - rabbitmq


volumes:
  postgres_data: